import type {
  AlternativesSeoEntry,
  BestTagSeoEntry,
} from "@/server/seo/types";

// Intentionally code-managed. Alternatives pages are required manual entries.
export const alternativesSeoRegistry: Record<string, AlternativesSeoEntry> = {
  shipfast: {
    slug: "shipfast",
    anchorToolSlug: "shipfast",
    title: "Best ShipFast Alternatives",
    intro: "Explore the best ShipFast alternatives. Compare top SaaS boilerplates and starter kits to launch your next product faster.",
    metaTitle: "7+ Best ShipFast Alternatives (SaaS Boilerplates) | ShipBoost",
    metaDescription: "Looking for ShipFast alternatives? Compare Makerkit, MkSaaS, supastarter, and more high-quality SaaS boilerplates for your next project.",
    toolSlugs: ["makerkit", "mksaas", "supastarter", "monokit", "saasbrella", "goilerplate"],
  },
  dirstarter: {
    slug: "dirstarter",
    anchorToolSlug: "dirstarter",
    title: "Best DirStarter Alternatives",
    intro: "Compare the best DirStarter alternatives for building SEO-ready directory businesses and resource hubs.",
    metaTitle: "Best DirStarter Alternatives for Directory Sites | ShipBoost",
    metaDescription: "Find the best DirStarter alternatives like DirectoryFast, DirectoryEasy, and more to launch your niche directory business fast.",
    toolSlugs: [
      "directoryfast",
      "directoryeasy",
      "directorystack",
      "nextjs-directory",
      "mkdirs",
      "supastarter",
      "goilerplate",
    ],
  },
  tapfiliate: {
    slug: "tapfiliate",
    anchorToolSlug: "tapfiliate",
    title: "Best Tapfiliate Alternatives",
    intro: "Compare Tapfiliate alternatives for managing your affiliate, referral, and partner programs.",
    metaTitle: "Best Tapfiliate Alternatives for Affiliate Management | ShipBoost",
    metaDescription: "Explore Tapfiliate alternatives like Rewardful, Tolt, and PromoteKit to scale your SaaS partnership revenue.",
    toolSlugs: ["rewardful", "trackdesk", "promotekit", "partnero", "tolt", "affonso", "tracknow"],
  },
  frase: {
    slug: "frase",
    anchorToolSlug: "frase",
    title: "Best Frase Alternatives",
    intro: "Looking for Frase alternatives? Compare the best AI SEO platforms to improve your search rankings and content performance.",
    metaTitle: "Best Frase Alternatives for AI SEO & Writing | ShipBoost",
    metaDescription: "Compare Frase alternatives like Surfer, Scalenut, and Outranking to automate your SEO content workflow.",
    toolSlugs: ["scalenut", "surfer", "outranking", "rankability", "aiseo", "seoengine", "blogseo"],
  },
  "vista-social": {
    slug: "vista-social",
    anchorToolSlug: "vista-social",
    title: "Best Vista Social Alternatives",
    intro: "Compare Vista Social alternatives for scheduling, managing, and growing your social media presence across channels.",
    metaTitle: "Best Vista Social Alternatives for Social Management | ShipBoost",
    metaDescription: "Explore Vista Social alternatives like Buffer, Sked Social, and Manychat to manage your social media workflows.",
    toolSlugs: ["sked-social", "sociamonials", "buffer", "manychat", "socialrails", "waalaxy", "octolens"],
  },
  pipedrive: {
    slug: "pipedrive",
    anchorToolSlug: "pipedrive",
    title: "Best Pipedrive Alternatives",
    intro: "Compare Pipedrive alternatives for managing your sales pipeline, prospecting, and outbound workflows.",
    metaTitle: "Best Pipedrive Alternatives for Sales CRM | ShipBoost",
    metaDescription: "Find the best Pipedrive alternatives like Close, Salesflare, and Apollo to streamline your sales engagement.",
    toolSlugs: ["close", "salesflare", "capsulecrm", "nutshell", "apollo", "reply", "folk"],
  },
  livechat: {
    slug: "livechat",
    anchorToolSlug: "livechat",
    title: "Best LiveChat Alternatives",
    intro: "Compare LiveChat alternatives for handling customer support, ticketing, and chat-based sales.",
    metaTitle: "Best LiveChat Alternatives for Support & Sales | ShipBoost",
    metaDescription: "Explore LiveChat alternatives like Intercom, Tidio, and HelpDesk to improve your customer communication.",
    toolSlugs: ["intercom", "tidio", "helpdesk", "chatbot", "jivochat", "sleekflow", "respond-io"],
  },
  zendesk: {
    slug: "zendesk",
    anchorToolSlug: "zendesk",
    title: "Best Zendesk Alternatives",
    intro: "Compare the best Zendesk alternatives for help desk, ticketing, and customer support workflows.",
    metaTitle: "Best Zendesk Alternatives for Customer Support | ShipBoost",
    metaDescription: "Explore Zendesk alternatives like Freshdesk, Help Scout, Intercom, and Front for teams comparing modern support platforms.",
    toolSlugs: ["freshdesk", "help-scout", "intercom", "front", "zoho-desk", "liveagent", "gorgias"],
  },
  freshdesk: {
    slug: "freshdesk",
    anchorToolSlug: "freshdesk",
    title: "Best Freshdesk Alternatives",
    intro: "Compare the best Freshdesk alternatives for support teams evaluating ticketing, automation, and customer service software.",
    metaTitle: "Best Freshdesk Alternatives for Support Teams | ShipBoost",
    metaDescription: "Compare Freshdesk alternatives like Zendesk, Help Scout, Intercom, and Zoho Desk to find the right support stack for your team.",
    toolSlugs: ["zendesk", "help-scout", "intercom", "zoho-desk", "liveagent", "front", "crisp"],
  },
  intercom: {
    slug: "intercom",
    anchorToolSlug: "intercom",
    title: "Best Intercom Alternatives",
    intro: "Compare the best Intercom alternatives for customer support, live chat, and customer messaging workflows.",
    metaTitle: "Best Intercom Alternatives for Support and Messaging | ShipBoost",
    metaDescription: "Explore Intercom alternatives like Help Scout, Crisp, Front, and Zendesk for teams comparing modern support and messaging platforms.",
    toolSlugs: ["help-scout", "crisp", "front", "zendesk", "freshdesk", "tidio", "gorgias"],
  },
  helpscout: {
    slug: "helpscout",
    anchorToolSlug: "help-scout",
    title: "Best Help Scout Alternatives",
    intro: "Compare the best Help Scout alternatives for teams that want simpler customer support software with stronger ticketing or messaging options.",
    metaTitle: "Best Help Scout Alternatives for Lean Support Teams | ShipBoost",
    metaDescription: "Compare Help Scout alternatives like Freshdesk, Intercom, Zendesk, and Front for teams evaluating support software with different workflow styles.",
    toolSlugs: ["freshdesk", "intercom", "zendesk", "front", "crisp", "zoho-desk", "liveagent"],
  },
  "zoho-desk": {
    slug: "zoho-desk",
    anchorToolSlug: "zoho-desk",
    title: "Best Zoho Desk Alternatives",
    intro: "Compare the best Zoho Desk alternatives for teams evaluating ticketing, customer support workflows, and service desk software with stronger fit or simpler execution.",
    metaTitle: "Best Zoho Desk Alternatives for Support Teams | ShipBoost",
    metaDescription: "Compare Zoho Desk alternatives like Freshdesk, Zendesk, Help Scout, and Front for support teams comparing ticketing depth, value, and workflow fit.",
    toolSlugs: ["freshdesk", "zendesk", "help-scout", "liveagent", "front", "intercom", "gorgias"],
  },
  front: {
    slug: "front",
    anchorToolSlug: "front",
    title: "Best Front Alternatives",
    intro: "Compare the best Front alternatives for teams that want shared inbox collaboration, customer communication workflows, and modern support operations.",
    metaTitle: "Best Front Alternatives for Shared Inbox Support | ShipBoost",
    metaDescription: "Explore Front alternatives like Intercom, Help Scout, Zendesk, and Freshdesk for teams comparing collaborative support and inbox-first workflows.",
    toolSlugs: ["intercom", "help-scout", "zendesk", "freshdesk", "crisp", "liveagent", "zoho-desk"],
  },
  gorgias: {
    slug: "gorgias",
    anchorToolSlug: "gorgias",
    title: "Best Gorgias Alternatives",
    intro: "Compare the best Gorgias alternatives for ecommerce support, ticketing, and customer service workflows that need stronger fit outside a commerce-first stack.",
    metaTitle: "Best Gorgias Alternatives for Ecommerce Support Teams | ShipBoost",
    metaDescription: "Compare Gorgias alternatives like Zendesk, Freshdesk, Intercom, and Help Scout for teams evaluating ecommerce support and broader customer service platforms.",
    toolSlugs: ["zendesk", "freshdesk", "intercom", "help-scout", "front", "tidio", "zoho-desk"],
  },
  hubspot: {
    slug: "hubspot",
    anchorToolSlug: "hubspot",
    title: "Best HubSpot Alternatives",
    intro: "Compare the best HubSpot alternatives for teams evaluating CRM software with different tradeoffs around flexibility, pipeline focus, and platform breadth.",
    metaTitle: "Best HubSpot Alternatives for CRM Buyers | ShipBoost",
    metaDescription: "Compare HubSpot alternatives like Attio, Pipedrive, Zoho CRM, and Close for teams evaluating startup-friendly and sales-focused CRM options.",
    toolSlugs: ["attio", "pipedrive", "zoho-crm", "close", "freshsales", "salesflare", "folk"],
  },
  attio: {
    slug: "attio",
    anchorToolSlug: "attio",
    title: "Best Attio Alternatives",
    intro: "Compare the best Attio alternatives for startup teams that want a modern CRM but are also considering more traditional pipeline or relationship-management systems.",
    metaTitle: "Best Attio Alternatives for Startup CRM Teams | ShipBoost",
    metaDescription: "Explore Attio alternatives like HubSpot, Pipedrive, Folk, and Close for teams comparing modern startup CRM options and sales workflow fit.",
    toolSlugs: ["hubspot", "pipedrive", "folk", "close", "copper", "salesflare", "monday-crm"],
  },
  "zoho-crm": {
    slug: "zoho-crm",
    anchorToolSlug: "zoho-crm",
    title: "Best Zoho CRM Alternatives",
    intro: "Compare the best Zoho CRM alternatives for small businesses and growing sales teams that want different tradeoffs in CRM usability, automation, and pricing.",
    metaTitle: "Best Zoho CRM Alternatives for Sales Teams | ShipBoost",
    metaDescription: "Compare Zoho CRM alternatives like HubSpot, Pipedrive, Freshsales, and Salesflare for teams evaluating CRM value, pipeline workflows, and automation.",
    toolSlugs: ["hubspot", "pipedrive", "freshsales", "salesflare", "capsulecrm", "nutshell", "attio"],
  },
  mailchimp: {
    slug: "mailchimp",
    anchorToolSlug: "mailchimp",
    title: "Best Mailchimp Alternatives",
    intro: "Compare the best Mailchimp alternatives for small businesses and marketers evaluating email marketing tools with different tradeoffs in simplicity, automation, creator fit, and ecommerce depth.",
    metaTitle: "Best Mailchimp Alternatives for Email Marketing | ShipBoost",
    metaDescription: "Compare Mailchimp alternatives like MailerLite, Brevo, ConvertKit, and ActiveCampaign for buyers evaluating practical email marketing platforms.",
    toolSlugs: ["mailerlite", "brevo", "convertkit", "activecampaign", "klaviyo", "beehiiv"],
  },
  mailerlite: {
    slug: "mailerlite",
    anchorToolSlug: "mailerlite",
    title: "Best MailerLite Alternatives",
    intro: "Compare the best MailerLite alternatives for small businesses and lean marketing teams evaluating email platforms with different tradeoffs in simplicity, automation, creator fit, and broader platform depth.",
    metaTitle: "Best MailerLite Alternatives for Email Marketing | ShipBoost",
    metaDescription: "Compare MailerLite alternatives like Mailchimp, Brevo, ConvertKit, and ActiveCampaign for buyers evaluating small-business email marketing platforms.",
    toolSlugs: ["mailchimp", "brevo", "convertkit", "activecampaign", "getresponse", "beehiiv"],
  },
  brevo: {
    slug: "brevo",
    anchorToolSlug: "brevo",
    title: "Best Brevo Alternatives",
    intro: "Compare the best Brevo alternatives for businesses evaluating email marketing and multichannel communication tools with different tradeoffs in automation, ecommerce fit, and broader messaging coverage.",
    metaTitle: "Best Brevo Alternatives for Email and SMS | ShipBoost",
    metaDescription: "Compare Brevo alternatives like Mailchimp, MailerLite, ActiveCampaign, and Klaviyo for buyers evaluating email marketing and multichannel communication platforms.",
    toolSlugs: ["mailchimp", "mailerlite", "activecampaign", "klaviyo", "getresponse", "constant-contact"],
  },
  convertkit: {
    slug: "convertkit",
    anchorToolSlug: "convertkit",
    title: "Best ConvertKit Alternatives",
    intro: "Compare the best ConvertKit alternatives for creators and audience-led businesses evaluating newsletter, email marketing, and automation tools beyond Kit's creator-first workflow.",
    metaTitle: "Best ConvertKit Alternatives for Creators and Newsletters | ShipBoost",
    metaDescription: "Explore ConvertKit alternatives like Beehiiv, Mailchimp, MailerLite, and ActiveCampaign for buyers comparing creator-first email and newsletter platforms.",
    toolSlugs: ["beehiiv", "mailchimp", "mailerlite", "activecampaign", "brevo", "klaviyo"],
  },
  activecampaign: {
    slug: "activecampaign",
    anchorToolSlug: "activecampaign",
    title: "Best ActiveCampaign Alternatives",
    intro: "Compare the best ActiveCampaign alternatives for businesses evaluating automation-heavy email marketing platforms with different tradeoffs in usability, ecommerce fit, and creator-led growth.",
    metaTitle: "Best ActiveCampaign Alternatives for Email Automation | ShipBoost",
    metaDescription: "Compare ActiveCampaign alternatives like Mailchimp, Brevo, Klaviyo, and ConvertKit for teams evaluating email automation and lifecycle marketing platforms.",
    toolSlugs: ["mailchimp", "brevo", "klaviyo", "convertkit", "mailerlite", "beehiiv"],
  },
  klaviyo: {
    slug: "klaviyo",
    anchorToolSlug: "klaviyo",
    title: "Best Klaviyo Alternatives",
    intro: "Compare the best Klaviyo alternatives for ecommerce brands and lifecycle marketers evaluating email and SMS platforms with different tradeoffs in automation depth, retention fit, and day-to-day usability.",
    metaTitle: "Best Klaviyo Alternatives for Ecommerce Email | ShipBoost",
    metaDescription: "Compare Klaviyo alternatives like Omnisend, Drip, Mailchimp, and ActiveCampaign for buyers evaluating ecommerce email, SMS, and retention marketing platforms.",
    toolSlugs: ["omnisend", "drip", "mailchimp", "activecampaign", "brevo", "mailerlite"],
  },
  typeform: {
    slug: "typeform",
    anchorToolSlug: "typeform",
    title: "Best Typeform Alternatives",
    intro: "Compare the best Typeform alternatives for teams evaluating online form builders with different tradeoffs in form design, workflow depth, and business fit.",
    metaTitle: "Best Typeform Alternatives for Online Forms | ShipBoost",
    metaDescription: "Compare Typeform alternatives like Jotform, Fillout, Tally, and Paperform for buyers evaluating modern online form builders.",
    toolSlugs: ["jotform", "fillout", "tally", "paperform", "surveymonkey", "formstack"],
  },
  jotform: {
    slug: "jotform",
    anchorToolSlug: "jotform",
    title: "Best Jotform Alternatives",
    intro: "Compare the best Jotform alternatives for teams evaluating general-purpose online forms, workflow-driven forms, and modern no-code form builders.",
    metaTitle: "Best Jotform Alternatives for Online Forms | ShipBoost",
    metaDescription: "Compare Jotform alternatives like Typeform, Fillout, Tally, and Formstack for teams evaluating online form builders with different workflow and UX tradeoffs.",
    toolSlugs: ["typeform", "fillout", "tally", "paperform", "formstack", "surveymonkey"],
  },
  surveymonkey: {
    slug: "surveymonkey",
    anchorToolSlug: "surveymonkey",
    title: "Best SurveyMonkey Alternatives",
    intro: "Compare the best SurveyMonkey alternatives for teams evaluating survey software, customer feedback tools, and broader online form builders.",
    metaTitle: "Best SurveyMonkey Alternatives for Surveys and Feedback | ShipBoost",
    metaDescription: "Compare SurveyMonkey alternatives like Typeform, Jotform, Formstack, and Fillout for teams evaluating surveys, forms, and research workflows.",
    toolSlugs: ["typeform", "jotform", "formstack", "fillout", "tally", "paperform"],
  },
  "google-forms": {
    slug: "google-forms",
    anchorToolSlug: "google-forms",
    title: "Best Google Forms Alternatives",
    intro: "Compare the best Google Forms alternatives for teams that want more branding, logic, workflow depth, payments, and customer-facing polish than a simple free form tool can provide.",
    metaTitle: "Best Google Forms Alternatives for Online Forms | ShipBoost",
    metaDescription: "Compare Google Forms alternatives like Typeform, Jotform, Fillout, Tally, and Paperform for buyers evaluating practical online form builders.",
    toolSlugs: ["typeform", "jotform", "fillout", "tally", "paperform", "cognito-forms", "wufoo"],
  },
  formstack: {
    slug: "formstack",
    anchorToolSlug: "formstack",
    title: "Best Formstack Alternatives",
    intro: "Compare the best Formstack alternatives for teams that want online forms, approvals, and workflow-heavy form systems with different usability and flexibility tradeoffs.",
    metaTitle: "Best Formstack Alternatives for Workflow Forms | ShipBoost",
    metaDescription: "Compare Formstack alternatives like Jotform, Typeform, Fillout, and Paperform for teams evaluating workflow-oriented online forms and business form systems.",
    toolSlugs: ["jotform", "typeform", "fillout", "paperform", "surveymonkey", "tally"],
  },
  calendly: {
    slug: "calendly",
    anchorToolSlug: "calendly",
    title: "Best Calendly Alternatives",
    intro: "Compare the best Calendly alternatives for small businesses evaluating scheduling apps with different tradeoffs in booking flow, pricing, and scheduling flexibility.",
    metaTitle: "Best Calendly Alternatives for Scheduling | ShipBoost",
    metaDescription: "Compare Calendly alternatives like SavvyCal, TidyCal, Acuity Scheduling, and Cal.com for buyers evaluating scheduling software for small business.",
    toolSlugs: ["savvycal", "tidycal", "acuity-scheduling", "cal-com"],
  },
  "acuity-scheduling": {
    slug: "acuity-scheduling",
    anchorToolSlug: "acuity-scheduling",
    title: "Best Acuity Scheduling Alternatives",
    intro: "Compare the best Acuity Scheduling alternatives for businesses evaluating appointment booking and scheduling tools with different tradeoffs in simplicity, flexibility, and booking flow quality.",
    metaTitle: "Best Acuity Scheduling Alternatives for Appointment Booking | ShipBoost",
    metaDescription: "Compare Acuity Scheduling alternatives like Calendly, SavvyCal, TidyCal, and Cal.com for teams evaluating small-business scheduling software.",
    toolSlugs: ["calendly", "savvycal", "tidycal", "cal-com"],
  },
  buffer: {
    slug: "buffer",
    anchorToolSlug: "buffer",
    title: "Best Buffer Alternatives",
    intro: "Compare the best Buffer alternatives for teams evaluating social media scheduling and publishing tools with different tradeoffs in workflow, content planning, and channel management.",
    metaTitle: "Best Buffer Alternatives for Social Scheduling | ShipBoost",
    metaDescription: "Compare Buffer alternatives like Later, Vista Social, Sked Social, and Sociamonials for buyers evaluating social media scheduling tools.",
    toolSlugs: ["later", "vista-social", "sked-social", "sociamonials"],
  },
  later: {
    slug: "later",
    anchorToolSlug: "later",
    title: "Best Later Alternatives",
    intro: "Compare the best Later alternatives for teams evaluating social media scheduling and publishing tools with different tradeoffs in planning workflows, visual scheduling, and operational fit.",
    metaTitle: "Best Later Alternatives for Social Scheduling | ShipBoost",
    metaDescription: "Compare Later alternatives like Buffer, Vista Social, Sked Social, and Sociamonials for buyers evaluating social scheduling software.",
    toolSlugs: ["buffer", "vista-social", "sked-social", "sociamonials"],
  },
  "sprout-social": {
    slug: "sprout-social",
    anchorToolSlug: "sprout-social",
    title: "Best Sprout Social Alternatives",
    intro: "Compare the best Sprout Social alternatives for teams evaluating social media management platforms with different tradeoffs in analytics depth, collaboration, publishing workflows, and pricing fit.",
    metaTitle: "Best Sprout Social Alternatives for Social Management | ShipBoost",
    metaDescription: "Compare Sprout Social alternatives like Hootsuite, Buffer, SocialBee, Publer, and Vista Social for buyers evaluating social media management software.",
    toolSlugs: ["hootsuite", "buffer", "socialbee", "publer", "vista-social", "later"],
  },
  socialbee: {
    slug: "socialbee",
    anchorToolSlug: "socialbee",
    title: "Best SocialBee Alternatives",
    intro: "Compare the best SocialBee alternatives for teams evaluating social media scheduling and management tools with different tradeoffs in content organization, evergreen posting, analytics, and broader workflow fit.",
    metaTitle: "Best SocialBee Alternatives for Social Scheduling | ShipBoost",
    metaDescription: "Compare SocialBee alternatives like Buffer, Later, Publer, Hootsuite, and Sprout Social for buyers evaluating social media management tools.",
    toolSlugs: ["buffer", "later", "publer", "hootsuite", "sprout-social", "vista-social"],
  },
  tally: {
    slug: "tally",
    anchorToolSlug: "tally",
    title: "Best Tally Alternatives",
    intro: "Compare the best Tally alternatives for teams evaluating lightweight online form builders with different tradeoffs in no-code flexibility, customer-facing polish, workflow depth, and survey fit.",
    metaTitle: "Best Tally Alternatives for Online Forms | ShipBoost",
    metaDescription: "Compare Tally alternatives like Fillout, Typeform, Jotform, Paperform, and Google Forms for buyers evaluating online form builders.",
    toolSlugs: ["fillout", "typeform", "jotform", "paperform", "google-forms", "formstack"],
  },
};

// Optional override layer for best-by-tag pages. Tools auto-load from DB tag membership.
export const bestTagSeoRegistry: Record<string, BestTagSeoEntry> = {};
