import type {
  AlternativesSeoEntry,
  BestTagSeoEntry,
} from "@/server/seo/types";

// Intentionally code-managed. Alternatives pages are required manual entries.
export const alternativesSeoRegistry: Record<string, AlternativesSeoEntry> = {
  shipfast: {
    slug: "shipfast",
    anchorToolSlug: "shipfast",
    title: "Best ShipFast Alternatives",
    intro: "Explore the best ShipFast alternatives. Compare top SaaS boilerplates and starter kits to launch your next product faster.",
    metaTitle: "7+ Best ShipFast Alternatives (SaaS Boilerplates) | ShipBoost",
    metaDescription: "Looking for ShipFast alternatives? Compare Makerkit, MkSaaS, supastarter, and more high-quality SaaS boilerplates for your next project.",
    toolSlugs: ["makerkit", "mksaas", "supastarter", "monokit", "saasbrella", "goilerplate"],
  },
  dirstarter: {
    slug: "dirstarter",
    anchorToolSlug: "dirstarter",
    title: "Best DirStarter Alternatives",
    intro: "Compare the best DirStarter alternatives for building SEO-ready directory businesses and resource hubs.",
    metaTitle: "Best DirStarter Alternatives for Directory Sites | ShipBoost",
    metaDescription: "Find the best DirStarter alternatives like DirectoryFast, DirectoryEasy, and more to launch your niche directory business fast.",
    toolSlugs: [
      "directoryfast",
      "directoryeasy",
      "directorystack",
      "nextjs-directory",
      "mkdirs",
      "supastarter",
      "goilerplate",
    ],
  },
  tapfiliate: {
    slug: "tapfiliate",
    anchorToolSlug: "tapfiliate",
    title: "Best Tapfiliate Alternatives",
    intro: "Compare Tapfiliate alternatives for managing your affiliate, referral, and partner programs.",
    metaTitle: "Best Tapfiliate Alternatives for Affiliate Management | ShipBoost",
    metaDescription: "Explore Tapfiliate alternatives like Rewardful, Tolt, and PromoteKit to scale your SaaS partnership revenue.",
    toolSlugs: ["rewardful", "trackdesk", "promotekit", "partnero", "tolt", "affonso", "tracknow"],
  },
  frase: {
    slug: "frase",
    anchorToolSlug: "frase",
    title: "Best Frase Alternatives",
    intro: "Looking for Frase alternatives? Compare the best AI SEO platforms to improve your search rankings and content performance.",
    metaTitle: "Best Frase Alternatives for AI SEO & Writing | ShipBoost",
    metaDescription: "Compare Frase alternatives like Surfer, Scalenut, and Outranking to automate your SEO content workflow.",
    toolSlugs: ["scalenut", "surfer", "outranking", "rankability", "aiseo", "seoengine", "blogseo"],
  },
  "vista-social": {
    slug: "vista-social",
    anchorToolSlug: "vista-social",
    title: "Best Vista Social Alternatives",
    intro: "Compare Vista Social alternatives for scheduling, managing, and growing your social media presence across channels.",
    metaTitle: "Best Vista Social Alternatives for Social Management | ShipBoost",
    metaDescription: "Explore Vista Social alternatives like Buffer, Sked Social, and Manychat to manage your social media workflows.",
    toolSlugs: ["sked-social", "sociamonials", "buffer", "manychat", "socialrails", "waalaxy", "octolens"],
  },
  pipedrive: {
    slug: "pipedrive",
    anchorToolSlug: "pipedrive",
    title: "Best Pipedrive Alternatives",
    intro: "Compare Pipedrive alternatives for managing your sales pipeline, prospecting, and outbound workflows.",
    metaTitle: "Best Pipedrive Alternatives for Sales CRM | ShipBoost",
    metaDescription: "Find the best Pipedrive alternatives like Close, Salesflare, and Apollo to streamline your sales engagement.",
    toolSlugs: ["close", "salesflare", "capsulecrm", "nutshell", "apollo", "reply", "folk"],
  },
  livechat: {
    slug: "livechat",
    anchorToolSlug: "livechat",
    title: "Best LiveChat Alternatives",
    intro: "Compare LiveChat alternatives for handling customer support, ticketing, and chat-based sales.",
    metaTitle: "Best LiveChat Alternatives for Support & Sales | ShipBoost",
    metaDescription: "Explore LiveChat alternatives like Intercom, Tidio, and HelpDesk to improve your customer communication.",
    toolSlugs: ["intercom", "tidio", "helpdesk", "chatbot", "jivochat", "sleekflow", "respond-io"],
  },
  zendesk: {
    slug: "zendesk",
    anchorToolSlug: "zendesk",
    title: "Best Zendesk Alternatives",
    intro: "Compare the best Zendesk alternatives for help desk, ticketing, and customer support workflows.",
    metaTitle: "Best Zendesk Alternatives for Customer Support | ShipBoost",
    metaDescription: "Explore Zendesk alternatives like Freshdesk, Help Scout, Intercom, and Front for teams comparing modern support platforms.",
    toolSlugs: ["freshdesk", "help-scout", "intercom", "front", "zoho-desk", "liveagent", "gorgias"],
  },
  freshdesk: {
    slug: "freshdesk",
    anchorToolSlug: "freshdesk",
    title: "Best Freshdesk Alternatives",
    intro: "Compare the best Freshdesk alternatives for support teams evaluating ticketing, automation, and customer service software.",
    metaTitle: "Best Freshdesk Alternatives for Support Teams | ShipBoost",
    metaDescription: "Compare Freshdesk alternatives like Zendesk, Help Scout, Intercom, and Zoho Desk to find the right support stack for your team.",
    toolSlugs: ["zendesk", "help-scout", "intercom", "zoho-desk", "liveagent", "front", "crisp"],
  },
  intercom: {
    slug: "intercom",
    anchorToolSlug: "intercom",
    title: "Best Intercom Alternatives",
    intro: "Compare the best Intercom alternatives for customer support, live chat, and customer messaging workflows.",
    metaTitle: "Best Intercom Alternatives for Support and Messaging | ShipBoost",
    metaDescription: "Explore Intercom alternatives like Help Scout, Crisp, Front, and Zendesk for teams comparing modern support and messaging platforms.",
    toolSlugs: ["help-scout", "crisp", "front", "zendesk", "freshdesk", "tidio", "gorgias"],
  },
  helpscout: {
    slug: "helpscout",
    anchorToolSlug: "help-scout",
    title: "Best Help Scout Alternatives",
    intro: "Compare the best Help Scout alternatives for teams that want simpler customer support software with stronger ticketing or messaging options.",
    metaTitle: "Best Help Scout Alternatives for Lean Support Teams | ShipBoost",
    metaDescription: "Compare Help Scout alternatives like Freshdesk, Intercom, Zendesk, and Front for teams evaluating support software with different workflow styles.",
    toolSlugs: ["freshdesk", "intercom", "zendesk", "front", "crisp", "zoho-desk", "liveagent"],
  },
  "zoho-desk": {
    slug: "zoho-desk",
    anchorToolSlug: "zoho-desk",
    title: "Best Zoho Desk Alternatives",
    intro: "Compare the best Zoho Desk alternatives for teams evaluating ticketing, customer support workflows, and service desk software with stronger fit or simpler execution.",
    metaTitle: "Best Zoho Desk Alternatives for Support Teams | ShipBoost",
    metaDescription: "Compare Zoho Desk alternatives like Freshdesk, Zendesk, Help Scout, and Front for support teams comparing ticketing depth, value, and workflow fit.",
    toolSlugs: ["freshdesk", "zendesk", "help-scout", "liveagent", "front", "intercom", "gorgias"],
  },
  front: {
    slug: "front",
    anchorToolSlug: "front",
    title: "Best Front Alternatives",
    intro: "Compare the best Front alternatives for teams that want shared inbox collaboration, customer communication workflows, and modern support operations.",
    metaTitle: "Best Front Alternatives for Shared Inbox Support | ShipBoost",
    metaDescription: "Explore Front alternatives like Intercom, Help Scout, Zendesk, and Freshdesk for teams comparing collaborative support and inbox-first workflows.",
    toolSlugs: ["intercom", "help-scout", "zendesk", "freshdesk", "crisp", "liveagent", "zoho-desk"],
  },
  gorgias: {
    slug: "gorgias",
    anchorToolSlug: "gorgias",
    title: "Best Gorgias Alternatives",
    intro: "Compare the best Gorgias alternatives for ecommerce support, ticketing, and customer service workflows that need stronger fit outside a commerce-first stack.",
    metaTitle: "Best Gorgias Alternatives for Ecommerce Support Teams | ShipBoost",
    metaDescription: "Compare Gorgias alternatives like Zendesk, Freshdesk, Intercom, and Help Scout for teams evaluating ecommerce support and broader customer service platforms.",
    toolSlugs: ["zendesk", "freshdesk", "intercom", "help-scout", "front", "tidio", "zoho-desk"],
  },
  hubspot: {
    slug: "hubspot",
    anchorToolSlug: "hubspot",
    title: "Best HubSpot Alternatives",
    intro: "Compare the best HubSpot alternatives for teams evaluating CRM software with different tradeoffs around flexibility, pipeline focus, and platform breadth.",
    metaTitle: "Best HubSpot Alternatives for CRM Buyers | ShipBoost",
    metaDescription: "Compare HubSpot alternatives like Attio, Pipedrive, Zoho CRM, and Close for teams evaluating startup-friendly and sales-focused CRM options.",
    toolSlugs: ["attio", "pipedrive", "zoho-crm", "close", "freshsales", "salesflare", "folk"],
  },
  attio: {
    slug: "attio",
    anchorToolSlug: "attio",
    title: "Best Attio Alternatives",
    intro: "Compare the best Attio alternatives for startup teams that want a modern CRM but are also considering more traditional pipeline or relationship-management systems.",
    metaTitle: "Best Attio Alternatives for Startup CRM Teams | ShipBoost",
    metaDescription: "Explore Attio alternatives like HubSpot, Pipedrive, Folk, and Close for teams comparing modern startup CRM options and sales workflow fit.",
    toolSlugs: ["hubspot", "pipedrive", "folk", "close", "copper", "salesflare", "monday-crm"],
  },
  "zoho-crm": {
    slug: "zoho-crm",
    anchorToolSlug: "zoho-crm",
    title: "Best Zoho CRM Alternatives",
    intro: "Compare the best Zoho CRM alternatives for small businesses and growing sales teams that want different tradeoffs in CRM usability, automation, and pricing.",
    metaTitle: "Best Zoho CRM Alternatives for Sales Teams | ShipBoost",
    metaDescription: "Compare Zoho CRM alternatives like HubSpot, Pipedrive, Freshsales, and Salesflare for teams evaluating CRM value, pipeline workflows, and automation.",
    toolSlugs: ["hubspot", "pipedrive", "freshsales", "salesflare", "capsulecrm", "nutshell", "attio"],
  },
};

// Optional override layer for best-by-tag pages. Tools auto-load from DB tag membership.
export const bestTagSeoRegistry: Record<string, BestTagSeoEntry> = {};
